CREATE TABLE user_levels (
	id INTEGER UNSIGNED AUTO_INCREMENT PRIMARY KEY,
	name VARCHAR(255) NOT NULL,
	grade INTEGER UNSIGNED NOT NULL
	
);


CREATE TABLE users (
	id INTEGER AUTO_INCREMENT PRIMARY KEY,
	user_name VARCHAR(50) NOT NULL,
	nickname VARCHAR(100) ,
	PASSWORD CHAR(255),
	user_levels_id INTEGER UNSIGNED NOT NULL,
	updated_at TIMESTAMP,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY (user_levels_id) REFERENCES user_levels(id)
);

